### PR TITLE
Style header

### PR DESCRIPTION
**Pull request by mikeyrayvon**
- adds squiggle underlines to header nav elements with hover animations
- doesn't style mobile nav

### CODE REVIEW

**Comment by varffs** [comment]
Looks good. Only possible issue is that the borders are outside of the hoverable area so if you hover the border you are not on the link and the animation doesnt happen. Maybe we can't solve this cleanly?

**Comment by mikeyrayvon** [comment]
i guess i intentionally excluded them...? i'll try to bring them in and commit it to see how that feels

**Comment by mikeyrayvon** [comment]
actually i don't think it's worth fussing over. we just went over budget :/ lets just keep moving

**Comment by varffs** [comment]
:/

**Pull request merged**
