### PR TITLE
Feat nav dropdown

### PR DESCRIPTION
**Pull request by mikeyrayvon**
show/hide product types menus in header on collection item hover

### CODE REVIEW

**Comment by varffs** [comment]
Sorry can't fully review this rn but I think this should be on click not hover.

**Comment by mikeyrayvon** [comment]
but then theres no way to get into the collection without selecting a product type. that doesnt feel right

**Comment by mikeyrayvon** [comment]
what if i just want to see all the Men's stuff?

**Comment by varffs** [comment]
I don't understand the objection. I would suggest it would work exactly as now except with clicks. So when you click on Men that is shown until you click again on Men or you click on another collection. 

I really don't like the hover (and it won't work for mobile if we want that) especially because the trigger areas are too small making it too easy to close the nav by mistake.

However the code is fine so will merge once conflicts are fixed

**Pull request merged**
